SELECT * FROM EMP
SELECT MAX(SAL) FROM EMP
SELECT MAX(HIREDATE) FROM EMP
SELECT MAX(ENAME) FROM EMP
SELECT MAX(LEN(ENAME)) FROM EMP

SELECT MIN(SAL) FROM EMP
SELECT MIN(HIREDATE) FROM EMP
SELECT MIN(ENAME) FROM EMP


SELECT SUM(SAL) FROM EMP
WHERE JOB = 'MANAGER'

SELECT SUM(SAL + COMM) FROM EMP
SELECT SUM(SAL + ISNULL(COMM, 0)) FROM EMP

SELECT SUM(CASE JOB WHEN 'CLERK' THEN SAL END) AS CLERK,
SUM(CASE JOB WHEN 'MANAGER' THEN SAL END) AS MANAGER,
SUM(CASE JOB WHEN 'SALESMAN' THEN SAL END) AS SAL
FROM EMP

SELECT AVG(SAL) AS AVERAGE_SAL FROM EMP
SELECT FLOOR(AVG(SAL)) FROM EMP

SELECT COUNT(EMPNO) FROM EMP
SELECT COUNT(COMM) FROM EMP
SELECT COUNT(*) FROM EMP

SELECT COUNT(*) FROM EMP
SELECT * FROM EMP
SELECT COUNT(*) AS EMP_JOINING_YEAR
FROM EMP
WHERE YEAR(HIREDATE) = 1981

SELECT COUNT(1) AS EMP_JOIND_ON_SUNDAY
FROM EMP
WHERE DATENAME(DW,HIREDATE) = 'SUNDAY'

SELECT COUNT(CASE DEPTNO WHEN 10 THEN EMPNO END) AS [10],
		COUNT(CASE DEPTNO WHEN 20 THEN EMPNO END) AS [20],
		COUNT(CASE DEPTNO WHEN 30 THEN EMPNO END) AS [30]
FROM EMP
/*1]Find The salary of employee */
SELECT SUM(SAL) FROM EMP

/*2]Find the average salary of all employees.*/
SELECT AVG(SAL) AS AVG_SAL FROM EMP
/*3]Find the highest salary in the company. */
SELECT MAX(SAL) AS MAX_SAL FROM EMP
/*4]Find the lowest salary in the company.*/
SELECT MIN(SAL) AS MIN_SAL FROM EMP
/*5]Count how many employees are working. */
SELECT COUNT(*) AS NO_OF_EMP FROM EMP
/*6]Count how many employees belong to department 30.*/
SELECT COUNT(*) 
FROM EMP
WHERE DEPTNO = 30
/*7]Find total salary department-wise.*/
SELECT DEPTNO, SUM(SAL) AS TOT_SAL
FROM EMP
GROUP BY DEPTNO
/*8]Find average salary job-wise. */
SELECT JOB, AVG(SAL) AS TOT_SAL
FROM EMP
GROUP BY JOB
/*9]Find number of managers in the company.*/
SELECT COUNT(*) AS NO_OF_MANAGER
FROM EMP
WHERE JOB = 'MANAGER'

/*10]Find the maximum salary in each department.*/
SELECT MAX(SAL) AS MAXIMUM_SAL 
FROM EMP
GROUP BY DEPTNO
/*11]Find the minimum salary in each job role.*/
SELECT MIN(SAL) AS MINIMUM_sal 
FROM EMP
GROUP BY JOB
/*12]Find total commission earned by salesmen.*/
SELECT SUM(COMM) AS TOTAL_COMM
FROM EMP
WHERE JOB = 'SALSEMAN'
/*13]Count employees who do not have a manager (MGR is NULL).*/
SELECT COUNT(*) AS NOT_MANAGER
FROM EMP
WHERE 'MANAGER' IS NULL

/*14]Count employees who have commission.*/
SELECT COUNT(*) AS COMM_GET 
FROM EMP
WHERE COMM IS NOT NULL AND COMM<> 0

/*15]Find total salary + commission for each employee.*/
SELECT ENAME, SAL + ISNULL(COMM, 0 ) AS TOTAL_EARNING
FROM EMP