SELECT * FROM SALESMART
SELECT ID, SDATE, AMT,
SUM(AMT) OVER(ORDER BY SDATE ASC) AS RUNNING_TOTAL
FROM SALESMART

SELECT ID, SDATE, AMT,
LAG(AMT,1) OVER(ORDER BY SDATE ASC) AS PREVIOUS_DAY_AMT,
AMT - LAG(AMT,1) OVER(ORDER BY SDATE ASC) AS GROWTH
FROM SALESMART

WITH S
AS
(
	SELECT ID, SDATE,AMT,
	LAG(AMT,1) OVER(ORDER BY SDATE ASC) AS PREVIOUS_DAY_AMT,
	AMT- LAG(AMT,1) OVER (ORDER BY SDATE ASC) AS GROWTH
	FROM SALESMART
)
SELECT ID, SDATE, AMT, PREVIOUS_DAY_AMT, GROWTH,
CAST((GROWTH/PREVIOUS_DAY_AMT)*100 AS DECIMAL(4,1)) AS PERCENTAGE
FROM S

SELECT ID, SDATE, AMT,
AVG(AMT) OVER(ORDER BY SDATE ASC) AS MOVING_AVG
FROM SALESMART 
SELECT * FROM EMP
SELECT SUM(SAL),DEPTNO
FROM EMP
GROUP BY DEPTNO 
SELECT ENAME, DEPTNO, SUM(SAL) AS TOTAL FROM EMP
GROUP BY ENAME,DEPTNO
/*1]Total salary per department*/
SELECT ENAME, DEPTNO, SUM(SAL)
FROM EMP
GROUP BY ENAME, DEPTNO
/* 2]Average salary per department */
SELECT ENAME, DEPTNO, AVG(SAL) AS AVG_SAL
FROM EMP
GROUP BY ENAME, DEPTNO

/*3] Count employees per department */
SELECT ENAME, DEPTNO, COUNT(*) AS NO_OF_EMP
FROM EMP
GROUP BY ENAME, DEPTNO

/*4]Maximum salary per department */
SELECT ENAME, DEPTNO, MAX(SAL) AS MAX_SAL
FROM EMP
GROUP BY ENAME, DEPTNO

/*5]Minimum salary per department */
SELECT ENAME, DEPTNO, MIN(SAL) AS MINIMUM_SAL
FROM EMP
GROUP BY ENAME, DEPTNO

/*6]Total salary per job */
SELECT ENAME,DEPTNO ,SUM(SAL) AS TOT_SAL
FROM EMP
GROUP BY ENAME, DEPTNO

/*7]Count employees per job */
SELECT JOB, COUNT(*) AS TOTAL_EMP
FROM EMP
GROUP BY JOB

/*8]Average salary per job */
SELECT JOB, AVG(SAL) AS AVERGE_SAL
FROM EMP
GROUP BY JOB

/*9]Job count per department*/
SELECT DEPTNO,JOB, COUNT(DEPTNO) AS JOB_COUNT
FROM EMP
GROUP BY DEPTNO, JOB

/*10]Total commission per department */
SELECT DEPTNO, SUM(COMM) AS TOTAL_COMM
FROM EMP
GROUP BY DEPTNO

/*11]Count employees with commission by department*/
SELECT DEPTNO,COMM ,COUNT(*) AS NO_OF_EMP
FROM EMP
WHERE COMM IS NOT NULL
GROUP BY DEPTNO, COMM
/*12]Highest salary per job */
SELECT JOB, MAX(SAL) AS MAX_SAL
FROM EMP
GROUP BY JOB

/*13]. Count managers per department */
SELECT * FROM EMP
SELECT DEPTNO, ENAME, COUNT(*) AS TOTAL_MANAGER
FROM EMP
WHERE JOB = 'MANAGER'
GROUP BY DEPTNO, ENAME
/*14]Departments with total salary > 5000*/
SELECT DEPTNO, SUM(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING SUM(SAL) > 5000
/*15] Job-wise total salary for DEPT 30*/
SELECT JOB, SUM(SAL) AS JOB_WISE_TOTAL_SAL
FROM EMP
WHERE DEPTNO = 30
GROUP BY JOB
/*16]Count employees per manager */
SELECT MGR, COUNT(ENAME) AS NO_OF_EMP
FROM EMP
GROUP BY  MGR