SELECT * FROM EMP
SELECT EMPNO,  ENAME,SAL,
LAG(SAL,1) OVER (ORDER BY EMPNO ASC) AS PREVIOUS_SAL
FROM EMP
SELECT * FROM POPULATION

SELECT YEAR, POPULATION,
POPULATION - LAG(YEAR, 1) OVER(ORDER BY YEAR) AS GRWOTH
FROM POPULATION

SELECT YEAR, POPULATION,
POPULATION - LAG(POPULATION, 1) OVER (ORDER BY YEAR ASC) AS GROWTH_PCT,
(POPULATION - LAG(POPULATION, 1) OVER (ORDER BY YEAR ASC)) /
(LAG(POPULATION, 1) OVER(ORDER BY YEAR ASC)) * 100 AS PCT
FROM POPULATION

WITH P
AS
(
	SELECT YEAR, POPULATION,
	LAG(POPULATION,1) OVER(ORDER BY YEAR ASC) AS PREVIOUS_YR_POP,
	POPULATION- LAG(POPULATION, 1) OVER(ORDER BY YEAR ASC) AS GROWTH
	FROM POPULATION
)
SELECT YEAR, POPULATION, GROWTH, PREVIOUS_YR_POP,
CAST((GROWTH / PREVIOUS_YR_POP)* 100 AS DECIMAL(4,1)) AS PCT
FROM P


/*1]Show population of each year along with the previous year's population (using LAG) */
SELECT YEAR, POPULATION,
LAG(POPULATION,1) OVER(ORDER BY YEAR ASC) AS COMPARISON
FROM POPULATION
/*2]Calculate year-to-year population growth using LAG().*/
SELECT YEAR, POPULATION,
LAG(POPULATION,1) OVER(ORDER BY  YEAR ASC) AS PREVIOUS_YR,
POPULATION - LAG(POPULATION,1) OVER (ORDER BY YEAR ASC) AS GROWTH
FROM POPULATION
/*3]Calculate percentage population growth for each year using LAG().*/
WITH P
AS
(
	SELECT YEAR, POPULATION,
	LAG(POPULATION,1) OVER(ORDER BY YEAR ASC) AS PREVIOUS_YR_POP,
	POPULATION - LAG(POPULATION,1) OVER(ORDER BY YEAR ASC) AS GROWTH
	FROM POPULATION
)
SELECT YEAR, POPULATION, PREVIOUS_YR_POP, GROWTH,
CAST(( GROWTH/PREVIOUS_YR_POP)*100 AS DECIMAL(4,1)) AS PCT
FROM P
/*4]Show only years where population decreased compared to the previous year.*/
WITH P
AS
(

SELECT YEAR, POPULATION,
LAG(POPULATION,1) OVER(ORDER BY YEAR ASC) AS PREVIOUS_YR_POP,
POPULATION - LAG(POPULATION,1) OVER(ORDER BY YEAR ASC) AS GROWTH
FROM POPULATION
)
SELECT YEAR, POPULATION, PREVIOUS_YR_POP, GROWTH
FROM P
WHERE POPULATION < PREVIOUS_YR_POP

/*5]Identify the first year of data (LAG returns NULL).*/
	SELECT YEAR, POPULATION,
	LAG(POPULATION, 1) OVER(ORDER BY YEAR ASC) AS PREVIOUS_YR_POP
	FROM POPULATION
	WHERE LAG(POPULATION,1) OVER(ORDER BY YEAR ) IS NULL