SELECT * FROM EMP 
SELECT EMPNO, ENAME, SAL,
RANK() OVER(ORDER BY SAL DESC) AS RANK
FROM EMP

SELECT EMPNO, ENAME, SAL,
DENSE_RANK() OVER (ORDER BY SAL DESC) AS RANK
FROM EMP


--1] Write a query to display each employee’s name, job, salary, and their rank based on salary in descending order using RANK().
SELECT ENAME, JOB, SAL,
RANK() OVER(ORDER BY SAL DESC) AS RNK
FROM EMP
--2]Show employee name, department, salary, and their rank based on salary using DENSE_RANK().
SELECT ENAME, DEPTNO, SAL,
DENSE_RANK() OVER (ORDER BY SAL DESC) AS SALARY_RNK
FROM EMP
--3]Display employee name, department, salary, and their salary rank within their department using RANK().
SELECT ENAME, DEPTNO, SAL,
RANK() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) AS RNK
FROM EMP
--4] Rank employees by salary within each job role using DENSE_RANK().
SELECT * FROM EMP
SELECT ENAME, JOB, SAL,
DENSE_RANK()OVER (PARTITION BY JOB ORDER BY SAL DESC) AS JOB_DENSE_RANK
FROM EMP
--
SELECT ENAME, JOB, SAL,HIREDATE,
DENSE_RANK() OVER (ORDER BY SAL DESC, HIREDATE ASC) AS RNK
FROM EMP

WITH E
AS
(
	SELECT ENAME, SAL,
	DENSE_RANK() OVER (ORDER BY SAL  DESC) AS RNK
	FROM EMP
)
SELECT ENAME, SAL FROM E 
WHERE RNK <=3

WITH E
AS
(
	SELECT ENAME, SAL,
	DENSE_RANK() OVER (ORDER BY SAL DESC) AS RNK
	FROM EMP
)
SELECT ENAME, SAL
FROM E
WHERE RNK =5


SELECT ENAME, SAL, EMPNO,
ROW_NUMBER() OVER (ORDER BY EMPNO ASC) AS RNK
FROM EMP


WITH E
AS
(
	SELECT ENAME, EMPNO, SAL,
	ROW_NUMBER() OVER (ORDER BY EMPNO ASC) AS RNK
	FROM EMP
)
SELECT *
FROM E
WHERE RNK <= 5

WITH E
AS
(
	SELECT EMPNO, ENAME, SAL,
	ROW_NUMBER() OVER (ORDER BY EMPNO ASC) AS RNK
	FROM EMP
)
DELETE FROM E
WHERE RNK < = 3

SELECT * FROM EMP